# ansible/setup.yml
---
- name: Configure ephemeral GCP VM
  hosts: ephemeral
  become: yes
  tasks:
    - name: Install base packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      command: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

    - name: Add Docker repo
      command: |
        echo "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" >> /etc/apt/sources.list

    - name: apt-get update
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Pull Docker image
      command: docker pull marilee/devops:{{ lookup('env','GITHUB_SHA') }}

    - name: Run container
      command: docker run -d -p 8080:8080 --name java-app marilee/devops:{{ lookup('env','GITHUB_SHA') }}

    - name: Show Docker ps
      command: docker ps
