# ansible/setup.yml
---
- name: Configure GCP VM and run Docker container
  hosts: ephemeral
  become: yes  # We'll use sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.command: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
      args:
        warn: false

    - name: Add Docker repo
      ansible.builtin.command: |
        echo "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" >> /etc/apt/sources.list
      args:
        warn: false

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Pull container image
      ansible.builtin.command: >
        docker pull marilee/devops:{{ docker_tag }}

    - name: Run container on port 8080
      ansible.builtin.command: >
        docker run -d -p 8080:8080 --name java-app marilee/devops:{{ docker_tag }}

    - name: Check docker ps
      ansible.builtin.command: docker ps

    - name: (Optional) Show logs
      ansible.builtin.command: docker logs java-app
      register: container_logs

    - name: Debug logs
      debug:
        var: container_logs.stdout
